### ISSUE TITLE
Error compiling for board Seeeduino Wio Terminal.

### ISSUE THREAD

**Issue by gbernal** [khoih-prog/WebSockets_Generic#21]
### Describe the bug

BOARD_TYPE "SAMD SEEED_WIO_TERMINAL" fails to identify installed board. 
### Steps to Reproduce

Install seedstudio SAMD boards using the board manager https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

open the example WIOTerminal_WebSocketClient.ino available from Websocket_Generic for WIO_Terminal
 
compile sketch
### Expected behavior
example code should be able to compile and run on designated board.

### Actual behavior

Code fails when uploading to board

### Debug and AT-command log (if applicable)

C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:21:2: warning: #warning Using SEEED_WIO_TERMINAL [-Wcpp]

 #warning Using SEEED_WIO_TERMINAL

  ^~~~~~~

In file included from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/arch.h:49:0,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/debug.h:40,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/opt.h:52,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/ip_addr.h:40,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/esp/tcpip_adapter.h:44,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/esp/esp_event.h:25,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/esp/esp_event_loop.h:22,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/esp/esp_lib_unified.h:12,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/seeed_rpcUnified.h:11,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcWiFi\src/WiFiGeneric.h:26,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcWiFi\src/WiFiSTA.h:28,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcWiFi\src/WiFi.h:32,

                 from C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcWiFi\src/rpcWiFi.h:1,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:33:

C:\Users\gbernal\Documents\Arduino\libraries\Seeed_Arduino_rpcUnified\src/lwip/arch/cc.h:44:0: warning: "BYTE_ORDER" redefined

 #define BYTE_ORDER LITTLE_ENDIAN

 

In file included from c:\users\gbernal\appdata\local\arduino15\packages\seeeduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\sys\types.h:67:0,

                 from c:\users\gbernal\appdata\local\arduino15\packages\seeeduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\stdio.h:61,

                 from C:\Users\gbernal\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.2\cores\arduino/Print.h:23,

                 from C:\Users\gbernal\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.2\cores\arduino/Stream.h:26,

                 from C:\Users\gbernal\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.2\cores\arduino/HardwareSerial.h:24,

                 from C:\Users\gbernal\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.2\cores\arduino/Arduino.h:83,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_build_912138\sketch\WIOTerminal_WebSocketClient.ino.cpp:1:

c:\users\gbernal\appdata\local\arduino15\packages\seeeduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\machine\endian.h:20:0: note: this is the location of the previous definition

 #define BYTE_ORDER _BYTE_ORDER

 

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:101:0,

                 from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:67,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsVersion_Generic.h:70:0: warning: "WEBSOCKETS_GENERIC_VERSION_MINOR" redefined

 #define WEBSOCKETS_GENERIC_VERSION_MINOR    10

 

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:67:0,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:70:0: note: this is the location of the previous definition

 #define WEBSOCKETS_GENERIC_VERSION_MINOR      13

 

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:101:0,

                 from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:67,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsVersion_Generic.h:71:0: warning: "WEBSOCKETS_GENERIC_VERSION_PATCH" redefined

 #define WEBSOCKETS_GENERIC_VERSION_PATCH    1

 

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:67:0,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:71:0: note: this is the location of the previous definition

 #define WEBSOCKETS_GENERIC_VERSION_PATCH      0

 

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:101:0,

                 from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:67,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsVersion_Generic.h:73:0: warning: "WEBSOCKETS_GENERIC_VERSION_INT" redefined

 #define WEBSOCKETS_GENERIC_VERSION_INT      2010001

 

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:67:0,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:73:0: note: this is the location of the previous definition

 #define WEBSOCKETS_GENERIC_VERSION_INT        2013000

 

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:67:0,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:210:4: warning: #warning Use SAMD21/SAMD51 in WebSockets_Generic [-Wcpp]

   #warning Use SAMD21/SAMD51 in WebSockets_Generic

    ^~~~~~~

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:67:0,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:559:4: warning: #warning Using RTL8720DN Seeed_Arduino_rpcWiFi Library [-Wcpp]

   #warning Using RTL8720DN Seeed_Arduino_rpcWiFi Library

    ^~~~~~~

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:636:4: warning: #warning This network type Supporting SSL for WebSockets [-Wcpp]

   #warning This network type Supporting SSL for WebSockets

    ^~~~~~~

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic.h:816:0,

                 from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:67,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSockets_Generic-Impl.h:82:6: warning: #warning CORE_HAS_LIBB64 [-Wcpp]

     #warning CORE_HAS_LIBB64

      ^~~~~~~

In file included from C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic.h:247:0,

                 from C:\Users\gbernal\AppData\Local\Temp\arduino_modified_sketch_974006\WIOTerminal_WebSocketClient.ino:37:

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic-Impl.h:320:4: warning: #warning WEBSOCKETS_NETWORK_TYPE != NETWORK_ESP8266_ASYNC [-Wcpp]

   #warning WEBSOCKETS_NETWORK_TYPE != NETWORK_ESP8266_ASYNC

    ^~~~~~~

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic-Impl.h:342:4: warning: #warning HAS_SSL [-Wcpp]

   #warning HAS_SSL

    ^~~~~~~

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic-Impl.h:363:4: warning: #warning ESP32 or NETWORK_RTL8720DN [-Wcpp]

   #warning ESP32 or NETWORK_RTL8720DN

    ^~~~~~~

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic-Impl.h: In member function 'void WebSocketsClient::loop()':

C:\Users\gbernal\Documents\Arduino\libraries\WebSockets_Generic\src/WebSocketsClient_Generic-Impl.h:400:22: error: 'class WiFiClientSecure' has no member named 'setInsecure'

         _client.ssl->setInsecure();

                      ^~~~~~~~~~~

exit status 1
Error compiling for board Seeeduino Wio Terminal.
### Screenshots
![image](https://user-images.githubusercontent.com/3216974/154760467-3bc15b85-8e07-41ea-b6db-02f2720f13c7.png)

### Information

Please ensure to specify the following:

* Arduino IDE version 1.8.11
* `Seeeduino Wio Terminal.
* test example code
* Simplest possible steps to reproduce

OS - Windows 10 
  
### Example

```
Arduino IDE version: 1.8.13
ESP32 Core Version 1.0.5
OS: Ubuntu 20.04 LTS
Linux xy-Inspiron-3593 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Context:
I encountered an endless loop while trying to connect to Local WiFi.

Steps to reproduce:


Install seedstudio SAMD boards using the board manager https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

open the example WIOTerminal_WebSocketClient.ino available from Websocket_Generic for WIO_Terminal
 
compile sketch
### Additional context

Add any other context about the problem here.

**Comment by khoih-prog** [comment]
Hi @gbernal 

Thanks for using the library and reporting the bug.

The new [**WebSockets_Generic releases v2.14.1**](https://github.com/khoih-prog/WebSockets_Generic/releases/tag/v2.14.1) has just been published to fix the bug.

**Be sure to use the `Packages_Patches` of this library version v2.14.1+ to avoid compiler error.**

Best Regards,

---

### Release v2.14.1

1. Fix setInsecure() bug for WIO_Terminal.
5. Update `Packages' Patches` for `Seeeduino` core. Be sure to use the `Packages_Patches` of this library version v2.14.1+ to avoid compiler error.
---

![Selection_099](https://user-images.githubusercontent.com/57012152/154769836-5c0e393f-9dc2-417c-9a6a-6a9fcad59f95.png)
