### ISSUE TITLE
Multiple Definitions error when trying to access this library across files

### ISSUE THREAD

**Issue by Gbellport** [khoih-prog/WebSockets_Generic#29]
Hello,

- Board: Teensy4.1
- QNEthernet
- PlatformIO (Core v6.1.4)

I am having **multiple definitions** issues when trying to access this library across different files:
```
Compiling .pio\build\teensy41\src\main.cpp.o
Compiling .pio\build\teensy41\src\other_file.cpp.o
Linking .pio\build\teensy41\firmware.elf
.pio\build\teensy41\src\other_file.cpp.o: In function `WebSocketsClient::messageReceived(WSclient_t*, WSopcode_t, unsigned char*, unsigned int, bool)':
other_file.cpp:(.text._ZN16WebSocketsClient15messageReceivedEP10WSclient_t10WSopcode_tPhjb+0x0): multiple definition of `WebSocketsClient::messageReceived(WSclient_t*, WSopcode_t, unsigned char*, unsigned int, bool)'
.pio\build\teensy41\src\main.cpp.o:main.cpp:(.text._ZN16WebSocketsClient15messageReceivedEP10WSclient_t10WSopcode_tPhjb+0x0): first defined here
c:/users/gabri/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld.exe: Disabling relaxation: it will not work with multiple definitions
```

This is the simplest way I have been able to reproduce the error:
![image](https://user-images.githubusercontent.com/19672976/198117708-29f7d962-d951-4050-a27e-7c2163a6b44e.png)

I use a few libraries across my actual project in this manner (such as QNEthernet) so I am wondering if I need to change a few things in my project to use WebSockets_Generic in a similar way.

**Comment by khoih-prog** [comment]
Hi @Gbellport

This issue is closed / deleted because you didn't follow the minimal request to post the [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example).

Also it's better to do some research first why you got that issue.

Good Luck,
