### ISSUE TITLE
ESP32 + W5500 Test example

### ISSUE THREAD

**Issue by mbta009** [khoih-prog/WebSockets_Generic#6]
Hello, thank you for your efforts in creating this library
My project uses the ESP32 + W5500 module and the Websocket protocol.
I'm looking to use your library but it's confusing to me.
Which WebSockets2_Generic or WebSockets_Generic exactly?
Which ethernet Libraries should be selected ?! Ethernet2.h or EthernetLarge.h
Also, which example should be tested? Is there a roadmap?

thank you

**Comment by khoih-prog** [comment]
You have to spend time to research and test to know what's good for you and fit for your use case.

The only reasonable support is to help when you have some issue with the library usage (bug, etc.)

I wish I have all the time in the world to guide everybody through the basic steps, to compensate the minimum basic research they must spend time to do.

You can also try the simple [**SimpleWebSocket example**](https://github.com/khoih-prog/EthernetWebServer/tree/master/examples/HTTPClient/SimpleWebSocket) of [**EthernetWebServer Library**](https://github.com/khoih-prog/EthernetWebServer).
