### ISSUE TITLE
Support for WiFi101 and MKR1000 board

### ISSUE THREAD

**Issue by gagulik** [khoih-prog/WebSockets_Generic#7]
Could you add support for mkr1000 boards (Wifi101) and Ethernet?

**Comment by khoih-prog** [comment]
If you spend some more time to look at the supported boards, you can realized that **MKR1000 (SAMD21-based)** is currently supported. I'm frustrated that I have to spend some `free` time to deal with these simple issues and too many people still treat the open-source libraries such as `fast food`, which won't benefit them in the long run.

Check these examples and many more

1. [**WebSocketClient_W5500**](https://github.com/khoih-prog/WebSockets_Generic/tree/master/examples/W5500/WebSocketClient_W5500) for Ethernet W5500
2. [**WebSocketClient_ENC**](https://github.com/khoih-prog/WebSockets_Generic/tree/master/examples/ENC28J60/WebSocketClient_ENC) for ENC28J60 Ethernet
3. [**WebSocketClient_NINA**](https://github.com/khoih-prog/WebSockets_Generic/tree/master/examples/WiFiNINA/WebSocketClient_NINA) for WiFiNINA / WiFi101

I don't think I'll spend some more time here, unless there is some library's bug is well proven.
