### ISSUE TITLE
Arduino Mega + W5500

### ISSUE THREAD

**Issue by gr33egory** [khoih-prog/WebSockets_Generic#8]
What mods should i do to compile that Library?

I'm getting error "AVR Not supported"
"Get atmega branch"

**Comment by khoih-prog** [comment]
I'm sorry that this library doesn't support AVR Mega boards and I won't spend time to provide support for it.

If you insists using Mega, you can follow instructions in [**arduinoWebSockets**](https://github.com/Links2004/arduinoWebSockets) and post the issue you're experiencing there.

1. [**Supported Hardware**](https://github.com/Links2004/arduinoWebSockets#https://github.com/Links2004/arduinoWebSockets#supported-hardware)
2. [**Note**](https://github.com/Links2004/arduinoWebSockets#note)
